// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * CheckLogin checks if the current cookie is valid (refreshes if needed).
 * Returns true if logged in. Returns false and emits auth:need-login if not.
 */
export function CheckLogin(): $CancellablePromise<boolean> {
    return $Call.ByID(1638580176);
}

export function IsWSRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(842104930);
}

/**
 * StartLogin generates a QR code and starts polling for login.
 * Called by the frontend after it has navigated to the login page.
 */
export function StartLogin(): $CancellablePromise<void> {
    return $Call.ByID(274292800);
}

export function StartWS(port: number): $CancellablePromise<void> {
    return $Call.ByID(988647245, port);
}

export function StopWS(): $CancellablePromise<void> {
    return $Call.ByID(1343807171);
}

/**
 * SyncAuth returns the current cookie and refresh token from config.
 */
export function SyncAuth(): $CancellablePromise<string[]> {
    return $Call.ByID(640480724);
}

/**
 * SyncRoomId returns the current room ID from config.
 */
export function SyncRoomId(): $CancellablePromise<number> {
    return $Call.ByID(1033284720);
}
